version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_crud_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - redis
    networks:
      - laravel
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8988:80"                  #Porta para API
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-username}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-userpass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis_service
    networks:
      - laravel

volumes:
  postgres_data:

networks:
  laravel:
    driver: bridge
